import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5000/');
  await page.getByRole('button', { name: 'Contratar' }).nth(1).click();
  await page.locator('#paymentForm div').filter({ hasText: 'PayPal' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Correo de PayPal' }).click();
  await page.getByRole('textbox', { name: 'Correo de PayPal' }).fill('a@gmail.com');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Continuar con PayPal' }).click();
  await page.goto('http://localhost:5000/landpage.html');
  await page.getByRole('link', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('a@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('123');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('link', { name: 'Regístrate' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Completo' }).fill('a');
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('a@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).fill('123');
  await page.getByRole('textbox', { name: 'Confirmar Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Confirmar Contraseña' }).fill('123');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Crear Cuenta' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('a@gmail.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('123');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('button', { name: 'Contratar' }).nth(1).click();
  await page.locator('#paymentForm div').filter({ hasText: 'PayPal' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Correo de PayPal' }).click();
  await page.getByRole('textbox', { name: 'Correo de PayPal' }).fill('a@gmail.com');
  await page.getByRole('textbox', { name: 'Correo de PayPal' }).press('Enter');
  await page.getByRole('button', { name: 'Continuar con PayPal' }).click();
  await page.getByText('🚀 Landing Page Convert').click();
  await page.getByRole('button', { name: 'Features' }).click();
  await page.getByRole('button', { name: 'Content' }).click();
  await page.getByRole('textbox', { name: 'Website Title' }).click();
  await page.getByRole('textbox', { name: 'Website Title' }).fill('Mi sitio web de confianza');
  await page.getByRole('textbox', { name: 'Tagline' }).click();
  await page.getByRole('textbox', { name: 'Tagline' }).dblclick();
  await page.getByRole('textbox', { name: 'Tagline' }).click();
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Tagline' }).fill('Este sitio web se ha generado automaticamente');
  await page.getByRole('button', { name: 'Generate Website' }).click();
  await page.getByRole('button', { name: 'Preview' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Final Website' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Back to Customize' }).click();
  await page.getByRole('button', { name: 'Back to Templates' }).click();
  await page.getByRole('button', { name: 'Cerrar Sesión' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});
